### ISSUE TITLE
How to use `errorHandler` in an express-based framework

### ISSUE THREAD

**Issue by creynders** [bodenr/errors#6]
I'm working on a project using [keystone.js](http://keystonejs.com/). In case you don't know it, it's an express-based CMS. I wanted to integrate the 'errors'-module, however noticed I can't use  `errors.errorHandler` middleware. I think this is due to https://github.com/bodenr/errors/blob/master/lib/errors.js#L643
It checks for the presence of 'express' or 'connect' and only exports `errorHandler` in case one of those is found. However since my project doesn't depend on express _directly_ neither express nor connect are found and the errorHandler isn't exposed. Obviously I could add express to my dependencies, but I'd rather not, since it isn't used anywhere else.

Do you know of a workaround? ATM I simply don't use any of the express integration, but that's a bit of a shame IMO.

**Comment by bodenr** [comment]
No response from submitter.. Closing.
